export const photos = [
  {
    id: 1,
    src: "/congresso/galery01.jpg",
    title: "ABERTURA OFICIAL DO 27º CONGRESSO NACIONAL DAS APAES",
    category: "congressos",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: true,
    description: "Cerimônia de abertura do último congresso",
  },
  {
    id: 2,
    src: "/congresso/galery02.jpg",
    title: "Palestra sobre Inclusão Digital",
    category: "palestras",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: false,
    description: "Palestra sobre inclusão digital e tecnologias assistivas",
  },
  {
    id: 3,
    src: "/congresso/galery03.jpg",
    title: "Workshop de Artes",
    category: "workshops",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: false,
    description: "Participantes em atividade prática de artes",
  },
  {
    id: 4,
    src: "/congresso/galery04.jpg",
    title: "Momento de Integração",
    category: "inclusao",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: true,
    description: "Momento de integração entre participantes",
  },
  {
    id: 5,
    src: "/congresso/galery05.jpg",
    title: "Preparativos do Evento",
    category: "bastidores",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: false,
    description: "Equipe organizando os preparativos do evento",
  },
  {
    id: 6,
    src: "/congresso/galery06.jpg",
    title: "Mesa Redonda sobre Políticas Públicas",
    category: "palestras",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: false,
    description: "Discussão sobre políticas públicas para inclusão",
  },
  {
    id: 7,
    src: "/congresso/53365182857_3349ba0b1f_c.jpg",
    title: "Cerimônia de Encerramento",
    category: "congressos",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: true,
    description: "Show de encerramento do evento",
  },
  {
    id: 8,
    src: "/congresso/53366073631_543afd73ed_c.jpg",
    title: "Atividades Inclusivas",
    category: "inclusao",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: false,
    description: "Atividades inclusivas durante o congresso",
  },
  {
    id: 9,
    src: "/congresso/53366074211_b92da23c88_c.jpg",
    title: "Workshop de Capacitação",
    category: "workshops",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: false,
    description: "Sessão de capacitação para educadores",
  },
  {
    id: 10,
    src: "/congresso/53366218926_da48f1f7f7_c.jpg",
    title: "27º CONGRESSO NACIONAL DAS APAES - 30-11",
    category: "bastidores",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: false,
    description: "Voluntários trabalhando nos bastidores do evento",
  },
  {
    id: 11,
    src: "/congresso/53366419088_ffa60d46eb_c.jpg",
    title: "Networking entre Participantes",
    category: "congressos",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: false,
    description: "Participantes interagindo durante o evento",
  },
  {
    id: 12,
    src: "/congresso/53366862836_7b816d6344_c.jpg",
    title: "Apresentação Cultural",
    category: "inclusao",
    year: "2023",
    location: "Maceió, Alagoas",
    featured: true,
    description: "Apresentação cultural durante o congresso",
  },
];
