/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PalestrasRouteImport } from './routes/palestras'
import { Route as PalestrantesRouteImport } from './routes/palestrantes'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPainelIngressoRouteImport } from './routes/_authenticated/painel.ingresso'
import { Route as AuthenticatedPainelHistoricoRouteImport } from './routes/_authenticated/painel.historico'
import { Route as AuthenticatedPainelEventoRouteImport } from './routes/_authenticated/painel.evento'
import { Route as AuthenticatedPainelDataRouteImport } from './routes/_authenticated/painel.data'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PalestrasRoute = PalestrasRouteImport.update({
  id: '/palestras',
  path: '/palestras',
  getParentRoute: () => rootRouteImport,
} as any)
const PalestrantesRoute = PalestrantesRouteImport.update({
  id: '/palestrantes',
  path: '/palestrantes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPainelIngressoRoute =
  AuthenticatedPainelIngressoRouteImport.update({
    id: '/ingresso',
    path: '/ingresso',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelHistoricoRoute =
  AuthenticatedPainelHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelEventoRoute =
  AuthenticatedPainelEventoRouteImport.update({
    id: '/evento',
    path: '/evento',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelDataRoute = AuthenticatedPainelDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthenticatedPainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/palestrantes': typeof PalestrantesRoute
  '/palestras': typeof PalestrasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/painel/data': typeof AuthenticatedPainelDataRoute
  '/painel/evento': typeof AuthenticatedPainelEventoRoute
  '/painel/historico': typeof AuthenticatedPainelHistoricoRoute
  '/painel/ingresso': typeof AuthenticatedPainelIngressoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeria': typeof GaleriaRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/palestrantes': typeof PalestrantesRoute
  '/palestras': typeof PalestrasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/painel/data': typeof AuthenticatedPainelDataRoute
  '/painel/evento': typeof AuthenticatedPainelEventoRoute
  '/painel/historico': typeof AuthenticatedPainelHistoricoRoute
  '/painel/ingresso': typeof AuthenticatedPainelIngressoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/galeria': typeof GaleriaRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/palestrantes': typeof PalestrantesRoute
  '/palestras': typeof PalestrasRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/_authenticated/painel/data': typeof AuthenticatedPainelDataRoute
  '/_authenticated/painel/evento': typeof AuthenticatedPainelEventoRoute
  '/_authenticated/painel/historico': typeof AuthenticatedPainelHistoricoRoute
  '/_authenticated/painel/ingresso': typeof AuthenticatedPainelIngressoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeria'
    | '/inscricao'
    | '/login'
    | '/not-found'
    | '/palestrantes'
    | '/palestras'
    | '/quem-somos'
    | '/recuperar-senha'
    | '/painel'
    | '/painel/data'
    | '/painel/evento'
    | '/painel/historico'
    | '/painel/ingresso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeria'
    | '/inscricao'
    | '/login'
    | '/not-found'
    | '/palestrantes'
    | '/palestras'
    | '/quem-somos'
    | '/recuperar-senha'
    | '/painel'
    | '/painel/data'
    | '/painel/evento'
    | '/painel/historico'
    | '/painel/ingresso'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/galeria'
    | '/inscricao'
    | '/login'
    | '/not-found'
    | '/palestrantes'
    | '/palestras'
    | '/quem-somos'
    | '/recuperar-senha'
    | '/_authenticated/painel'
    | '/_authenticated/painel/data'
    | '/_authenticated/painel/evento'
    | '/_authenticated/painel/historico'
    | '/_authenticated/painel/ingresso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GaleriaRoute: typeof GaleriaRoute
  InscricaoRoute: typeof InscricaoRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  PalestrantesRoute: typeof PalestrantesRoute
  PalestrasRoute: typeof PalestrasRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palestras': {
      id: '/palestras'
      path: '/palestras'
      fullPath: '/palestras'
      preLoaderRoute: typeof PalestrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palestrantes': {
      id: '/palestrantes'
      path: '/palestrantes'
      fullPath: '/palestrantes'
      preLoaderRoute: typeof PalestrantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel/ingresso': {
      id: '/_authenticated/painel/ingresso'
      path: '/ingresso'
      fullPath: '/painel/ingresso'
      preLoaderRoute: typeof AuthenticatedPainelIngressoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/historico': {
      id: '/_authenticated/painel/historico'
      path: '/historico'
      fullPath: '/painel/historico'
      preLoaderRoute: typeof AuthenticatedPainelHistoricoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/evento': {
      id: '/_authenticated/painel/evento'
      path: '/evento'
      fullPath: '/painel/evento'
      preLoaderRoute: typeof AuthenticatedPainelEventoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/data': {
      id: '/_authenticated/painel/data'
      path: '/data'
      fullPath: '/painel/data'
      preLoaderRoute: typeof AuthenticatedPainelDataRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelDataRoute: typeof AuthenticatedPainelDataRoute
  AuthenticatedPainelEventoRoute: typeof AuthenticatedPainelEventoRoute
  AuthenticatedPainelHistoricoRoute: typeof AuthenticatedPainelHistoricoRoute
  AuthenticatedPainelIngressoRoute: typeof AuthenticatedPainelIngressoRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelDataRoute: AuthenticatedPainelDataRoute,
  AuthenticatedPainelEventoRoute: AuthenticatedPainelEventoRoute,
  AuthenticatedPainelHistoricoRoute: AuthenticatedPainelHistoricoRoute,
  AuthenticatedPainelIngressoRoute: AuthenticatedPainelIngressoRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GaleriaRoute: GaleriaRoute,
  InscricaoRoute: InscricaoRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  PalestrantesRoute: PalestrantesRoute,
  PalestrasRoute: PalestrasRoute,
  QuemSomosRoute: QuemSomosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
